[default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
    "3499977893", # Advanced Developer Tools's Workshop ID
    "1779063631", # ZEN
]

presets = []
dlc = []
optionals = []
parameters = []

[ace]
extends = "default"
workshop = [
    "463939057", # ACE
]
